<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<PackageId>BeaverX.Domain</PackageId>
		<Version>1.0.0-preview.3</Version>
		<Authors>hedonghua</Authors>
		<Company>BeaverX 开源社区</Company>
		<Description>BeaverX.Domain 是 BeaverX 快速开发框架的核心领域契约包。本包秉承实用主义 DDD 哲学，默认锁定高性能“雪花 ID（Int64/long）”作为全局实体主键。内置像素级对齐 ABP 的单文件全审计契约、防熔断当前用户上下文（ICurrentUser）以及纯异步、高性能的现代泛型仓储契约。</Description>
		<PackageTags>abp;ddd;snowflake;repository;domain;framework;net10;aot</PackageTags>
		<Copyright>Copyright © 2026 BeaverX</Copyright>

		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/hdonghua/BeaverX.NET</PackageProjectUrl>
		<RepositoryUrl>https://github.com/hdonghua/BeaverX.NET.git</RepositoryUrl>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\BeaverX.Core\BeaverX.Core.csproj" />
	</ItemGroup>

</Project>
