<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<PackageId>BeaverX.Core</PackageId>
		<Version>1.0.0-preview.2</Version>
		<Authors>hedonghua</Authors>
		<Description>BeaverX.Core 是一个专为现代 .NET 应用打造的高性能、轻量级、完全白盒化的模块化底层核心驱动引擎。它提供了高内聚的模块生命周期管理与全自动依赖注入扫描。</Description>
		<PackageTags>abp;modular;framework;dependency-injection;ioc;net10;aot</PackageTags>
		<Copyright>Copyright © 2026 BeaverX</Copyright>

		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/hdonghua/BeaverX.NET</PackageProjectUrl>
		<RepositoryUrl>https://github.com/hdonghua/BeaverX.NET.git</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
</Project>
